blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('label/', views.label, name='label'),
    path('archives/<str:arch>', views.archives, name='archives'),
    path('index/<int:pg>', views.index, name='index_num'),
    path('article/<int:article_id>', views.article, name='article'),
    path('hello/', views.hello, name='hello'),
    path('about/', views.about, name='about'),
    path('files/', views.files, name='files'),
]

extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

myblog/urls.py
import os


from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings
from DjangoUeditor import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ueditor/', include(urls)),
    path('', include('blog.urls')),
]

if settings.DEBUG:
    media_root = os.path.join(settings.BASE_DIR, settings.MEDIA_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=media_root)

blog/models.py
# coding=utf-8
from django.db import models

from DjangoUeditor.models import UEditorField

class Blog(models.Model):
    blog_title = models.CharField(max_length=100)
    blog_label = models.CharField(max_length=50)
    Content=UEditorField(u'文章',width=600, height=300, toolbars="full", imagePath="images/", filePath="files/", upload_settings={"imageMaxSize":1204000},
             settings={},command=None,blank=True)
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='发表时间')
    alter_time = models.DateTimeField(auto_now=True, verbose_name='修改时间')

    class Meta:
        db_table = 'Article'
        verbose_name = '文章'
        verbose_name_plural = verbose_name

blog/views.py
# -*- coding:utf-8 -*-
from django.shortcuts import render,get_object_or_404,get_list_or_404
from .models import *
from django.http import HttpResponse
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger

def index(request,pg=1):
    blog_all_list = Blog.objects.all()
    paginator = Paginator(blog_all_list, 2)
    page_num = request.GET.get('page',pg)
    page_of_blogs = paginator.get_page(page_num)
    count_list = [int(i) for i in range(1,paginator.num_pages+1)]
    return render(request, 'blog/index.html', {'art_list': page_of_blogs,'page_range':count_list,'now_page':pg})

def article(request,article_id):
    text = get_object_or_404(Blog,pk=article_id)
    context = {
        'title': text.blog_title,
        'label': text.blog_label,
        'alter_date': text.alter_time,
        'article' : text.Content,
    }
    return render(request,'blog/article.html',context)

def hello(request):
    return render(request,'blog/base.html')

def label(request):
    blog_all_list = Blog.objects.all()
    label_list = {}
    for blog in blog_all_list:
        if blog.blog_label in label_list:
            label_list[blog.blog_label] += 1
        else:
            label_list[blog.blog_label] = 1
    return render(request,'blog/label.html',{'label_list':list(label_list.items())})
def archives(request,arch):
    text = get_list_or_404(Blog, blog_label=arch)
    context = {
        'label': arch,
        'archives_list': text,
    }
    return render(request,'blog/archives.html',context)


def about(request):
    return render(request,'blog/about.html')

def files(request):
    text = Blog.objects.all()
    context = {
        'article_list': text,
    }
    return render(request,'blog/files.html',context)

blog/templates/blog/about.html
{% extends "blog/base.html" %}

{% block content1 %}
<div class="inner" id="content-inner">
      <article class="post page" id="page">
  <header class="post-header text-center">
  </header>
  <div class="post-content">

        <h2 id="Contact"><a href="#Contact" class="headerlink" title="Contact"></a>Contact</h2><ul>
<li>Email: <a href="m15584418917@163.com" target="_blank" rel="noopener">m15584418917@163.com</a></li>
<li>Github: <a href="https://github.com/yrzsp/" target="_blank" rel="noopener">https://github.com/yrzsp/</a></li>


  </div>
</article>
    </div>
{% endblock content1 %}

blog/templates/blog/archives.html
{% extends "blog/base.html" %}

{% block content1 %}

<div class="inner" id="content-inner">

<div class="page tag-page" id="tag">
  <h2 title="文章">{{label}}</h2>
    {% for archives in archives_list %}
        <div class="tag-item">

            <a href="{% url 'blog:article' archives.id %}">
              {{archives.blog_title}}
            </a>

          <time class="time" datetime="{{archives.alter_time}}">
            {{archives.alter_time}}
          </time>
        </div>
    {% endfor %}


</div>
    </div>

{% endblock content1 %}

blog/templates/blog/article.html
{% extends "blog/base.html" %}

{% block title %}
<title>{{title}}</title>
{% endblock title %}

{% block content1 %}
<!-------------------------------------------------------------------1--------------->
<article class="post" id="post">
    <header class="post-header text-center">
      <h1 class="title">
        {{title}}
      </h1>
      <span>

        <time class="time" datetime="{{alter_date}}">
        {{alter_date}}
      </time>

      </span>
      <span class="slash">/</span>
      <span class="post-meta">
      <span class="post-tags">
        <ul class="article-tag-list">
            <li class="article-tag-list-item">
                <a class="article-tag-list-link" href="{% url 'blog:archives' label %}">{{label}}</a>
            </li>
        </ul>
      </span>
    </span>
    </header>

    <div class="post-content">
        {{article|safe}}
    </div>

  </article>
<!---------------------------------------------------------------------------------->
{% endblock content1 %}

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
	<meta charset="UTF-8">
	<script type="text/javascript" src="static/blog/js/jquery-3.3.1.min.js"></script>
  	<script type="text/javascript" src="{% static 'blog/js/bootstrap.min.js' %}"></script>
  	<link rel="stylesheet" type="text/css" href="static/css/bootstrap.min.css">
  	<link rel="stylesheet" type="text/css" href="{% static 'blog/css/myblog.css' %}">
  	<link rel="icon" type="image/x-icon" href="{% static 'blog/images/logo.png' %}">
  	{% block title%}
    <title>python学习博客</title>
  	{% endblock title%}


    <!-- stylesheets list from config.yml -->

    <link rel="stylesheet" href="{% static 'blog/css/pure-min.css' %}">
  	<style type="text/css">

  	</style>
</head>
<body>
	<div class="nav-container">
    <nav class="home-menu pure-menu pure-menu-horizontal">
  <a class="pure-menu-heading" style="text-transform:none;" href="/">
    <img class="avatar" src="{% static 'blog/images/logo.png' %}">
    <span class="title">MyBlog</span>
  </a>

  <ul class="pure-menu-list clearfix">
      <li class="pure-menu-item actived"><a href="/" class="pure-menu-link">首页</a></li>

      <!--<li class="pure-menu-item"><a href="/archives" class="pure-menu-link">分类</a></li>-->

      <li class="pure-menu-item"><a href="/label" class="pure-menu-link">分类</a></li>

      <li class="pure-menu-item"><a href="/files" class="pure-menu-link">归档</a></li>

      <li class="pure-menu-item"><a href="/about" class="pure-menu-link">关于</a></li>


  </ul>

</nav>
  </div>

<div class="container" id="content-outer">
    <div class="inner" id="content-inner">

        {% block content1 %}
        {% endblock content1 %}

        <footer class="footer text-center">
    <div id="bottom-inner">
        <a class="bottom-item" href="https://www.onono.cn/">首页</a> |
        <a class="bottom-item" href="https://github.com/15584418917" target="_blank">GitHub</a> |
        <a class="bottom-item" href="https://bootstrap" target="_blank">Powered by yrzsp</a>
    </div>
</footer>
</body>
</html>

blog/templates/blog/files.html
{% extends "blog/base.html" %}

{% block content1 %}
    <div class="inner" id="content-inner">
        <section class="post page archives">
          <h3 class="archive-year-wrap">
            <a href="/archives/2019" class="archive-year">
              2019
            </a>
          </h3>


      {% for article in article_list %}
              <div class="archive">
              <a class="post-go" href="{% url 'blog:article' article.id %}">
                  <span class="date">
                    {{article.create_time}}
                  </span>
                  <span class="slash">/</span>
                  {{article.blog_title}}
              </div>
      {% endfor %}
{% endblock content1 %}

blog/templates/blog/hello.html
<ul class="pagination">
       <li > #按钮，点击左右翻页
            {% if page_of_blogs.has_previous %} #有下一页
               <a href="?page={{page_of_blogs.previous_page_number}}" aria-label="Previous">
                   <span aria-hidden="true">«</span>#点击跳转下一页
               </a>
            {% else %}#没有下一页，没有a标签，点击按钮不会跳转
               <span aria-hidden="true">«</span>
            {% endif %}
      </li> #显示分页的页码
            {% for page_num in page_of_blogs.paginator.page_range %}#对分页的每一页进行迭代
                 {% if page_num == page_of_blogs.number %} #如果有某一个页面是指定的页面
                      <li class="active"><a href="?page={{page_num}}">{{page_num}} </a></li>
                                        #就标记为cative，对应前端分页页码的显示会有颜色加深的效果
                         {% else %}
                      <li ><a href="?page={{page_num}}">{{page_num}} </a></li>#否则就显示分页页码
                 {% endif %}
            {% endfor %}
      <li> #按钮，点击翻页
            {% if page_of_blogs.has_next %}#如果后续有分页，按钮可点击
                  <a href="?page={{page_of_blogs.next_page_number}}" aria-label="Previous">
                      <span aria-hidden="true">«</span>
                  </a>
            {% else %}#没有分页，不可点击
                  <span aria-hidden="true">«</span>
            {% endif %}
     </li>
</ul>

{% for art in art_list %}
{{art.id}}-------{{art.blog_title}}
{% endfor %}

blog/templates/blog/index.html
{% extends "blog/base.html" %}

{% block content1 %}
{% for art in art_list %}
<br>
<article class="recent-post-item">
        <a class="title" href="{% url 'blog:article' art.id %}"><h2>{{art.blog_title}}</h2></a>
        <div class="post-meta">

          <time class="time" datetime="{{art.alter_time}}">
            {{art.alter_time}}&nbsp;/&nbsp;<a class="index-tag-list-link" href="{% url 'blog:article' art.id %}">{{art.blog_label}}</a>
          </time>

        </div>


          <div class="post-excerpt">
            <p>{{art.Content|striptags|truncatechars:100 }}</p>
          </div>

        <a class="more" href="{% url 'blog:article' art.id %}"> 阅读全文〉</a>
      </article>
{% endfor %}

{% if art_list.object_list and art_list.paginator.num_pages > 1 %}
<nav class="page-nav text-center">
    {% if art_list.has_previous %}
    <a class="extend prev" rel="prev" href="{% url 'blog:index_num' art_list.previous_page_number %}">〈</a>
    {% endif %}
    {% for page in page_range %}
    {% if pg == page %}
        <h3 style="color: blue;">{{page}}</h3>
    {% else %}
        <a class="page-number" href="{% url 'blog:index_num' page %}">{{page}}</a>
    {% endif %}
    {% endfor %}
    {% if art_list.has_next %}
    <a class="extend next" rel="next" href="{% url 'blog:index_num' art_list.next_page_number %}">〉</a>
    {% endif %}
</nav>
{% endif %}

{% endblock content1 %}

blog/templates/blog/label.html
{% extends "blog/base.html" %}

{% block content1 %}

<div class="inner" id="content-inner">
      <article class="post page" id="page">
  <header class="post-header text-center">
  </header>
  <div class="post-content">
      <ul class="tag-list">
          {% for key,value in label_list %}
          <li class="tag-list-item">
              <a class="tag-list-link" href="{% url 'blog:archives' key %}">{{key}}</a><span class="tag-list-count">{{value}}</span>
          </li>
          {% endfor %}
  </div>
</article>
    </div>



{% endblock content1 %}